### ISSUE TITLE
The to-do list

### ISSUE THREAD

**Issue by stal888** [tin-devs/tin-core#1]
- [ ] Public API
- [ ] Chat log object with persistence
- [ ] Abstract friend chats and group chats
- [ ] Abstract file transfers

Add more as needed

**Comment by alnf** [comment]
- [ ] What the hell is this? Sad tox replacement?
